from app.services.geocoding.provider_versions import PROVIDER_VERSION_CATALOG

SOURCE_RECORD_SCHEMA_VERSION = "1.1"

GAZETTEER_VERSION = "2026-04-03.1"
LOGICAL_LOCATION_CATALOG_VERSION = "2026-04-03.1"
LOCATION_RULESET_VERSION = "2026-04-08.3"
LIVE_LOCATION_BENCHMARK_VERSION = "labeled-live-2026-04-03.2"
GEOCODING_PROVIDER_CATALOG_VERSION = PROVIDER_VERSION_CATALOG

LOCATION_PIPELINE_VERSION = (
    "location-pipeline:"
    f"rules={LOCATION_RULESET_VERSION};"
    f"gazetteer={GAZETTEER_VERSION};"
    f"logical={LOGICAL_LOCATION_CATALOG_VERSION};"
    f"geocoding={GEOCODING_PROVIDER_CATALOG_VERSION}"
)
