from app.services.classifier.schemas import NewsCategory


CATEGORY_KEYWORDS: dict[NewsCategory, tuple[str, ...]] = {
    NewsCategory.TRAFIK_KAZASI: (
        # Guclu kaza sinyalleri
        "trafik kazası",
        "zincirleme kaza",
        "maddi hasarlı kaza",
        "yaralanmalı kaza",
        "ölümlü kaza",
        "kaza",
        "çarpışma",
        "çarptı",
        "çarpıştı",
        "takla",
        "devrildi",
        "devrilme",
        # Yol / guzergah baglami
        "yol kapandı",
        "trafik durdu",
        "kapanan yol",
        "tıkandı",
        "d100",
        "e5",
        "karayolu",
        "tem otoyolu",
        "tem yolu",
        "tem bağlantı yolu",
    ),
    NewsCategory.YANGIN: (
        # Yangin turleri
        "yangın",
        "alev",
        "tutuştu",
        "yandı",
        "yanıyor",
        "orman yangını",
        "bina yangını",
        "araç yangını",
        "fabrika yangını",
        "daire yangını",
        "iş yeri yangını",
        # Mudahale
        "itfaiye",
        "söndürme",
        "yangına müdahale",
        "alevlere müdahale",
        "itfaiye müdahalesi",
        "hortum",
        "yangın tüpü",
        "köpüklü",
        # Sonuclar
        "duman",
        "kül",
        "enkaz",
        "tahliye edildi",
        "mahsur kaldı",
    ),
    NewsCategory.HIRSIZLIK: (
        # Suç turleri
        "hırsızlık",
        "hırsız",
        "çalındı",
        "çalınma",
        "soygun",
        "gasp",
        "kapkaç",
        "dolandırıcılık",
        "nitelikli dolandırıcılık",
        "dolandırıldı",
        # Nesne / olay kaliplari
        "araç çalındı",
        "motosiklet çalındı",
        "para çalındı",
        "ev soyuldu",
        "iş yeri soyuldu",
        "banka soygunu",
        # Asayis agirlikli ek kaliplar
        "suç unsuru",
        "suç unsurları",
        "uyuşturucu madde",
        "ruhsatsız tabanca",
        "silahlı saldırı",
    ),
    NewsCategory.ELEKTRIK_KESINTISI: (
        # Guclu kesinti kaliplari
        "elektrik kesintisi",
        "elektrik kesildi",
        "elektrik arızası",
        "enerji kesintisi",
        "planlı kesinti",
        # Kurum / altyapi
        "kkedaş",
        "ayedaş",
        "toroslar edaş",
        "tedaş",
        "enerji şirketi",
        "dağıtım şirketi",
        "trafo",
        "trafo merkezi",
        "hat arızası",
        # Durum
        "karanlıkta kaldı",
        "ışıklar söndü",
        "jeneratör",
        "enerji yok",
    ),
    NewsCategory.KULTUREL_ETKINLIK: (
        # Kultur / sanat etkinlikleri
        "konser",
        "festival",
        "sergi",
        "tiyatro",
        "sinema",
        "kültürel etkinlik",
        "gösteri",
        # Organizasyon
        "kutlama",
        "anma töreni",
        "mezuniyet",
        "diploma töreni",
        "ödül töreni",
        "söyleşi",
        "atölye",
        # Kultur kurumlari
        "müze",
        "kültür merkezi",
        "sanat galerisi",
        "resital",
        "sempozyum",
        "kongre",
        "konferans",
        "kütüphane haftası",
        "farkındalık günü",
        "öğrenci buluşması",
        "anlamlı etkinlik",
        "fuar",
        "kitap fuarı",
        # Etkinlik niteligi tasiyan spor organizasyonlari
        "turnuva",
        "şampiyona",
        "yarışma",
    ),
}
