from __future__ import annotations

# NOTE: This file is source-backed on purpose so CI/test environments do not depend on
# Python-version-specific .pyc restore artifacts.

DISTRICT_DISPLAY_NAMES = ('İzmit',
 'Gebze',
 'Darıca',
 'Gölcük',
 'Hereke',
 'Körfez',
 'Kartepe',
 'Başiskele',
 'Çayırova',
 'Dilovası',
 'Kandıra',
 'Karamürsel',
 'Derince')

NEIGHBORHOODS_BY_DISTRICT = {'Başiskele': ('Aksığın',
               'Altınkent',
               'Atakent',
               'Aydınkent',
               'Barbaros',
               'Camidüzü',
               'Damlar',
               'Doğantepe',
               'Döngel',
               'Fatih',
               'Havuzlubahçe',
               'Karadenizliler',
               'Karşıyaka',
               'Kazandere',
               'Kılıçaslan',
               'Körfez',
               'Kullar-Tepecik',
               'Kullar-Yakacık',
               'Mahmutpaşa',
               'Mehmetağa',
               'Ovacık',
               'Paşadağ',
               'Sahil',
               'Sepetlipınar',
               'Serdar',
               'Serindere',
               'Servetiyecami',
               'Servetiyekarşı',
               'Seymen',
               'Şehitekrem',
               'Tepecik',
               'Vezirçiftliği',
               'Yaylacık',
               'Yeniköy-Merkez',
               'Yeşilkent',
               'Yeşilyurt',
               'Yuvacık-Yakacık'),
 'Çayırova': ('Atatürk', 'Cumhuriyet', 'Çayırova', 'Emek', 'İnönü', 'Özgürlük', 'Şekerpınar', 'Yenimahalle'),
 'Darıca': ('Bağlarbaşı',
            'Bayramoğlu',
            'Cami',
            'Emek',
            'Fevzi Çakmak',
            'Kazım Karabekir',
            'Nenehatun',
            'Osman Gazi',
            'Pirireis',
            'Sırasöğütler',
            'Yalı',
            'Yeni',
            'Zincirlikuyu'),
 'Derince': ('Çenedağ',
             'Çınarlı',
             'Deniz',
             'Dumlupınar',
             'Fatih Sultan',
             'Geredeli',
             'İbni Sina',
             'Karagöllü',
             'Kaşıkçı',
             'Mersincik',
             'Sırrıpaşa',
             'Tahtalı',
             'Terziler',
             'Toylar',
             'Yavuzsultan',
             'Yenikent'),
 'Dilovası': ('Çerkeşli',
              'Demirciler',
              'Dil İskelesi',
              'Fatih',
              'Kayapınar',
              'Köseler',
              'Mimar Sinan',
              'Orhangazi',
              'Tavşancıl',
              'Tepecik',
              'Turgut Özal'),
 'Gebze': ('Ahatlı',
           'Arapçeşme',
           'Balçık',
           'Barış',
           'Beylikbağı',
           'Cumaköy',
           'Cumhuriyet',
           'Denizli',
           'Duraklı',
           'Elbizli',
           'Eskihisar',
           'Gaziler',
           'Güzeller',
           'Hacı Halil',
           'Hatipler',
           'Hürriyet',
           'İnönü',
           'İstasyon',
           'Kadıllı',
           'Kargalı',
           'Kirazpınar',
           'Köşklüçeşme',
           'Mevlana',
           'Mimar Sinan',
           'Mollafenari',
           'Muallimköy',
           'Mudarlı',
           'Mustafapaşa',
           'Osman Yılmaz',
           'Ovacık',
           'Pelitli',
           'Sultan Orhan',
           'Tatlıkuyu',
           'Tavşanlı',
           'Tepemanayır',
           'Ulus',
           'Yağcılar',
           'Yavuzselim',
           'Yenikent'),
 'Gölcük': ('Değirmendere-Atatürk',
            'Değirmendere-Cumhuriyet',
            'Değirmendere-Merkez',
            'Değirmendere-Topçular',
            'Değirmendere-Yalı',
            'Değirmendere-Yukarı',
            'Değirmendere-Yüzbaşılar',
            'Donanma',
            'Dumlupınar',
            'Düzağaç',
            'Eskiferhadiye',
            'Ferhadiye',
            'Halıdere-Körfez',
            'Halıdere-Yalı',
            'Halıdere-Yeni',
            'Hamidiye',
            'Hasaneyn',
            'Hisareyn-Karaköprü',
            'Hisareyn-Merkez',
            'İcadiye',
            'İhsaniye-Çiftlik',
            'İhsaniye-Denizevler',
            'İhsaniye-Merkez',
            'İpekyolu',
            'İrşadiye',
            'Kavaklı',
            'Lütfiye',
            'Mamuriye',
            'Merkez',
            'Mesruriye',
            'Nimetiye',
            'Nüzhetiye',
            'Örcün',
            'Panayır',
            'Piyalepaşa',
            'Saraylı',
            'Selimiye',
            'Siyretiye',
            'Sofular',
            'Şehitler',
            'Şevketiye',
            'Şirinköy',
            'Ulaşlı-Yalı',
            'Ulaşlı-Yavuz Sultan Selim',
            'Ümmiye',
            'Yazlık-Merkez',
            'Yazlık-Yenimahalle',
            'Yeni Mahalle',
            'Yunusemre'),
 'İzmit': ('Akarca',
           'Akçakoca',
           'Akmeşe-Atatürk',
           'Akmeşe-Cumhuriyet',
           'Akpınar',
           'Alikahya-Atatürk',
           'Alikahya-Cumhuriyet',
           'Alikahya-Fatih',
           'Ambarcı',
           'Arızlı',
           'Arpalıkihsaniye',
           'Ayazma',
           'Bağlıca',
           'Balören',
           'Bayraktar',
           'Bekirdere',
           'Biberoğlu',
           'Böğürgen',
           'Bulduk',
           'Cedid',
           'Çağırğan',
           'Çavuşoğlu',
           'Çayırköy',
           'Çubuklubala',
           'Çubukluosmaniye',
           'Çukurbağ',
           'Dağköy',
           'Doğan',
           'Durhasan',
           'Düğmeciler',
           'Emirhan',
           'Erenler',
           'Eseler',
           'Fethiye',
           'Fevziçakmak',
           'Gedikli',
           'Gökçeören',
           'Gülbahçe Kadriye',
           'Gültepe',
           'Gündoğdu',
           'Güvercinlik',
           'Hacı Hasan',
           'Hacıhızır',
           'Hakaniye',
           'Hasancıklar',
           'Hatip',
           'İzmit-Cumhuriyet',
           'İzmit Fatih',
           'Kabaoğlu',
           'Kadıköy',
           'Karaabdülbaki',
           'Karabaş',
           'Karadenizliler',
           'Kaynarca',
           'Kemalpaşa',
           'Kısalar',
           'Kocatepe',
           'Kozluca',
           'Kozluk',
           'Körfez',
           'Kulfallı',
           'Kulmahmut',
           'Kurtdere',
           'Kuruçeşme-Fatih',
           'M. Ali Paşa',
           'Malta',
           'Mecidiye',
           'Merkez',
           'Nebihoca',
           'Orhan',
           'Orhaniye',
           'Ortaburun',
           'Ömerağa',
           'Sanayi',
           'Sapakpınar',
           'Sarışeyh',
           'Sekbanlı',
           'Sepetçi',
           'Serdar',
           'Sultaniye',
           'Süleymaniye',
           'Süverler',
           'Şahinler',
           'Şirintepe',
           'Tavşantepe',
           'Tepecik',
           'Tepeköy',
           'Terzibayırı',
           'Topçular',
           'Turgut',
           'Tüysüzler',
           'Veliahmet',
           'Yahya Kaptan',
           'Yassıbağ',
           'Yenice',
           'Yenidoğan',
           'Yenimahalle',
           'Yenişehir',
           'Yeşilova',
           'Zabıtan',
           'Zeytinburnu'),
 'Kandıra': ('Ahmethacılar',
             'Akbal',
             'Akçabeyli',
             'Akçakese',
             'Akçaova',
             'Akdurak',
             'Akıncı',
             'Alefli',
             'Antaplı',
             'Avdan',
             'Aydınlık',
             'Babaköy',
             'Babalı',
             'Bağırganlı',
             'Balaban',
             'Balcı',
             'Ballar',
             'Beyce',
             'Beylerbeyi',
             'Bolu',
             'Bozburun',
             'Cebeci',
             'Çakırcaali',
             'Çakmaklar',
             'Çalca',
             'Çalköy',
             'Çalyer',
             'Çamkonak',
             'Çarşı',
             'Çerçili',
             'Dalca',
             'Deliveli',
             'Doğancılı',
             'Döngelli',
             'Duraçali',
             'Duraklı',
             'Eğercili',
             'Elmacık',
             'Esentepe',
             'Ferizli',
             'Gebeşler',
             'Goncaaydın',
             'Hacılar',
             'Hacımazlı',
             'Hacışeyh',
             'Hediyeli',
             'Hıdırlar',
             'Hüdaverdiler',
             'İncecik',
             'Kabaağaç',
             'Kanatlar',
             'Karaağaç',
             'Karadivan',
             'Karlı',
             'Kaymas',
             'Kaymaz Erikli',
             'Kefken',
             'Kerpe',
             'Kırkarmut',
             'Kızılcapınar',
             'Kocakaymas',
             'Kubuzcu',
             'Kurtyeri',
             'Lokmanlı',
             'Mancarlar',
             'Merkez Erikli',
             'Mülküşehsuvar',
             'Nasuhlar',
             'Orhan',
             'Ömerli',
             'Özbey',
             'Pelitpınarı',
             'Pınardüzü',
             'Pınarlı',
             'Pirceler',
             'Safalı',
             'Sarıahmetler',
             'Sarıcaali',
             'Sarıgazi',
             'Sarnıçlar',
             'Selametli',
             'Selimköy',
             'Sepetçi',
             'Seyitaliler',
             'Sinanlıbilalli',
             'Sucuali',
             'Süllü',
             'Şerefsungur',
             'Tatarahmet',
             'Teksen',
             'Terziler',
             'Topluca',
             'Üğümce',
             'Yağcılar',
             'Yusufca'),
 'Karamürsel': ('Akçat',
                'Akpınar',
                'Avcıköy',
                'Çamçukur',
                'Çamdibi',
                'Dereköy',
                'Ereğli',
                'Fulacık',
                'Hayriye',
                'İhsaniye',
                'İnebeyli',
                'Kadriye',
                'Karaahmetli',
                'Karapınar',
                'Kayacık',
                'Kızderbent',
                'Oluklu',
                'Osmaniye',
                'Pazarköy',
                'Safiye',
                'Semetler',
                'Senaiye',
                'Suludere',
                'Tahtalı',
                'Tepeköy',
                'Yalakdere'),
 'Kartepe': ('Arslanbey',
             'Ataevler',
             'Ataşehir',
             'Avluburun',
             'Balaban',
             'Çepni',
             'Derbent',
             'Dumlupınar',
             'Emekevler',
             'Ertuğrul Gazi',
             'Eşme',
             'Eşmeahmediye',
             'Fatih Sultan Mehmet',
             'İbrikdere',
             'İstasyon',
             'Karatepe',
             'Ketenciler',
             'Köseköy',
             'Maşukiye',
             'Nusretiye',
             'Pazarçayırı',
             'Rahmiye',
             'Sarımeşe',
             'Serinlik',
             'Suadiye',
             'Sultaniye',
             'Şevkatiye',
             'Şirinsulhiye',
             'Uzunbey',
             'Uzunçiftlik',
             'Uzuntarla'),
 'Körfez': ('Agah Ateş',
            'Alihocalar',
            'Atalar',
            'Barbaros',
            'Belen',
            'Cumaköy',
            'Cumhuriyet',
            'Çamlıtepe',
            'Çıraklı',
            'Dereköy',
            'Dikenli',
            'Elmacık',
            'Esentepe',
            'Fatih',
            'Güney',
            'Hacı Akif',
            'Hacı Osman',
            'Himmetli',
            'İlimtepe',
            'Kalburcu',
            'Karayakuplu',
            'Kışladüzü',
            'Kirazlıyalı',
            'Kutluca',
            'Kuzey',
            'Mimar Sinan',
            'Naipköy',
            'Osmanlı',
            'Sevindikli',
            'Sipahiler',
            'Şemsettin Naci',
            'Şirinyalı',
            'Yavuz Sultan Selim',
            'Yeni Yalı',
            'Yukarı Hereke')}

STRONG_NEIGHBORHOOD_ALIASES = {('İzmit', 'Yahya Kaptan'): ('Yahya Kaptan',),
 ('İzmit', 'Bekirdere'): ('Bekirdere',),
 ('İzmit', 'Kabaoğlu'): ('Kabaoğlu', 'Umuttepe'),
 ('İzmit', 'Şirintepe'): ('Şirintepe',),
 ('Gebze', 'Beylikbağı'): ('Beylikbağı',),
 ('Gebze', 'Sultan Orhan'): ('Sultan Orhan',),
 ('Darıca', 'Bayramoğlu'): ('Bayramoğlu',),
 ('Çayırova', 'Şekerpınar'): ('Şekerpınar',),
 ('Dilovası', 'Tavşancıl'): ('Tavşancıl',),
 ('Kandıra', 'Kefken'): ('Kefken',),
 ('Kandıra', 'Kerpe'): ('Kerpe',),
 ('Kandıra', 'Cebeci'): ('Cebeci',),
 ('Kandıra', 'Bağırganlı'): ('Bağırganlı',),
 ('Karamürsel', 'İhsaniye'): ('İhsaniye',),
 ('Kartepe', 'Maşukiye'): ('Maşukiye', 'Masukiye'),
 ('Kartepe', 'Sarımeşe'): ('Sarımeşe',),
 ('Kartepe', 'Suadiye'): ('Suadiye',),
 ('Kartepe', 'Uzuntarla'): ('Uzuntarla',),
 ('Körfez', 'Kirazlıyalı'): ('Kirazlıyalı',)}

CURATED_VENUES = ({'canonical_name': 'Kocaeli Bilim Merkezi',
  'feature_type': 'venue',
  'district': 'İzmit',
  'aliases': ('Kocaeli Bilim Merkezi', 'Bilim Merkezi'),
  'source_key': 'kbb_bilim_merkezi',
  'allow_fuzzy': True},
 {'canonical_name': 'Ormanya Doğal Yaşam Parkı',
  'feature_type': 'venue',
  'district': 'Kartepe',
  'aliases': ('Ormanya', 'Ormanya Doğal Yaşam Parkı'),
  'source_key': 'kbb_ormanya',
  'allow_fuzzy': True},
 {'canonical_name': 'Kocaeli Uluslararası Kongre Merkezi',
  'feature_type': 'venue',
  'district': 'İzmit',
  'aliases': ('Kocaeli Uluslararası Kongre Merkezi', 'Kocaeli Kongre Merkezi', 'Kongre Merkezi'),
  'source_key': 'kbb_kongre_merkezi',
  'allow_fuzzy': True},
 {'canonical_name': 'Gölcük Kültür ve Kongre Merkezi',
  'feature_type': 'venue',
  'district': 'Gölcük',
  'aliases': ('Gölcük Kültür ve Kongre Merkezi',),
  'source_key': 'kbb_golcuk_kongre',
  'allow_fuzzy': True},
 {'canonical_name': 'Darıca Kültür ve Kongre Merkezi',
  'feature_type': 'venue',
  'district': 'Darıca',
  'aliases': ('Darıca Kültür ve Kongre Merkezi',),
  'source_key': 'kbb_darica_kongre',
  'allow_fuzzy': True},
 {'canonical_name': 'Körfez Kongre Merkezi',
  'feature_type': 'venue',
  'district': 'Körfez',
  'aliases': ('Körfez Kongre Merkezi',),
  'source_key': 'kbb_korfez_kongre',
  'allow_fuzzy': True},
 {'canonical_name': 'Sekapark',
  'feature_type': 'venue',
  'district': 'İzmit',
  'aliases': ('Sekapark', 'Seka Park'),
  'source_key': 'kbb_sekapark',
  'allow_fuzzy': True},
 {'canonical_name': 'Kocaeli Şehirlerarası Otobüs Terminali',
  'feature_type': 'transport_hub',
  'district': 'İzmit',
  'aliases': ('Kocaeli Şehirlerarası Otobüs Terminali',
              'İzmit Otogar',
              'Kocaeli Otogar',
              'Şehirlerarası Otobüs Terminali'),
  'source_key': 'ulasimpark_terminal',
  'allow_fuzzy': True},
 {'canonical_name': 'Kocaeli Stadyumu',
  'feature_type': 'stadium',
  'district': 'İzmit',
  'aliases': ('Kocaeli Stadyumu', 'Yıldız Entegre Kocaeli Stadyumu', 'TURKA Araç Muayene Kocaeli Stadyumu'),
  'source_key': 'tff_kocaeli_stadyumu',
  'allow_fuzzy': True},
 {'canonical_name': 'Gebze Alaettin Kurt Stadyumu',
  'feature_type': 'stadium',
  'district': 'Gebze',
  'aliases': ('Gebze Alaettin Kurt Stadyumu', 'Alaettin Kurt Stadyumu'),
  'source_key': 'tff_gebze_stadyumu',
  'allow_fuzzy': True},
 {'canonical_name': 'Darıca İlçe Stadyumu',
  'feature_type': 'stadium',
  'district': 'Darıca',
  'aliases': ('Darıca İlçe Stadyumu', 'Darıca Stadyumu'),
  'source_key': 'tff_darica_stadyumu',
  'allow_fuzzy': True},
 {'canonical_name': 'Kocaeli Şehir Hastanesi',
  'feature_type': 'hospital',
  'district': 'İzmit',
  'aliases': ('Kocaeli Şehir Hastanesi', 'Şehir Hastanesi'),
  'source_key': 'saglik_kocaeli_sehir',
  'allow_fuzzy': True},
 {'canonical_name': 'Kocaeli Devlet Hastanesi',
  'feature_type': 'hospital',
  'district': 'İzmit',
  'aliases': ('Kocaeli Devlet Hastanesi',),
  'source_key': 'saglik_kocaeli_devlet',
  'allow_fuzzy': True},
 {'canonical_name': 'Derince Eğitim ve Araştırma Hastanesi',
  'feature_type': 'hospital',
  'district': 'Derince',
  'aliases': ('Derince Eğitim ve Araştırma Hastanesi', 'Derince EAH'),
  'source_key': 'saglik_derince_eah',
  'allow_fuzzy': True},
 {'canonical_name': 'Gebze Fatih Devlet Hastanesi',
  'feature_type': 'hospital',
  'district': 'Gebze',
  'aliases': ('Gebze Fatih Devlet Hastanesi',),
  'source_key': 'saglik_gebze_fatih',
  'allow_fuzzy': True},
 {'canonical_name': 'Darıca Farabi Eğitim ve Araştırma Hastanesi',
  'feature_type': 'hospital',
  'district': 'Darıca',
  'aliases': ('Darıca Farabi Eğitim ve Araştırma Hastanesi', 'Farabi Hastanesi', 'Darıca Farabi'),
  'source_key': 'saglik_darica_farabi',
  'allow_fuzzy': True},
 {'canonical_name': 'VM Medical Park Kocaeli Hastanesi',
  'feature_type': 'hospital',
  'district': 'İzmit',
  'aliases': ('VM Medical Park Kocaeli Hastanesi', 'Medical Park Kocaeli'),
  'source_key': 'saglik_ozel_tesisler',
  'allow_fuzzy': True},
 {'canonical_name': 'Anadolu Sağlık Merkezi',
  'feature_type': 'hospital',
  'district': 'Gebze',
  'aliases': ('Anadolu Sağlık Merkezi',),
  'source_key': 'saglik_ozel_tesisler',
  'allow_fuzzy': True},
 {'canonical_name': 'Kocaeli Üniversitesi Umuttepe Kampüsü',
  'feature_type': 'campus',
  'district': 'İzmit',
  'aliases': ('Kocaeli Üniversitesi Umuttepe Kampüsü', 'Umuttepe Kampüsü', 'Umuttepe', 'KOÜ Umuttepe'),
  'source_key': 'kocaeli_uni',
  'allow_fuzzy': True},
 {'canonical_name': 'Kocaeli Üniversitesi Hastanesi',
  'feature_type': 'hospital',
  'district': 'İzmit',
  'aliases': ('Kocaeli Üniversitesi Hastanesi', 'KOÜ Hastanesi', 'Umuttepe Hastanesi'),
  'source_key': 'kocaeli_uni',
  'allow_fuzzy': True},
 {'canonical_name': 'Gebze Teknik Üniversitesi Kampüsü',
  'feature_type': 'campus',
  'district': 'Gebze',
  'aliases': ('Gebze Teknik Üniversitesi Kampüsü', 'GTÜ Kampüsü', 'Gebze Teknik Üniversitesi'),
  'source_key': 'gtu_kampus',
  'allow_fuzzy': True},
 {'canonical_name': 'Paribu Cineverse 41 Burda AVM',
  'feature_type': 'cinema',
  'district': 'İzmit',
  'aliases': ('Paribu Cineverse 41 Burda AVM', '41 Burda Sinema', '41 Burda AVM Sineması'),
  'source_key': 'cineverse_41burda',
  'allow_fuzzy': True},
 {'canonical_name': 'Paribu Cineverse Gebze Center AVM',
  'feature_type': 'cinema',
  'district': 'Gebze',
  'aliases': ('Paribu Cineverse Gebze Center AVM', 'Gebze Center Sinema', 'Gebze Center AVM Sineması'),
  'source_key': 'cineverse_gebze_center',
  'allow_fuzzy': True},
 {'canonical_name': 'Symbol Kocaeli AVM Sinemaları',
  'feature_type': 'cinema',
  'district': 'Başiskele',
  'aliases': ('Symbol Kocaeli AVM Sinemaları', 'Symbol Sinema', 'Symbol AVM Sinema'),
  'source_key': 'symbol_sinema',
  'allow_fuzzy': True},
 {'canonical_name': 'Karamursel Ilce Stadi',
  'feature_type': 'stadium',
  'district': 'Karamursel',
  'aliases': ('Karamursel Ilce Stadi', 'Karamursel Stadyumu'),
  'source_key': 'tff_karamursel_stadyumu',
  'allow_fuzzy': True},
 {'canonical_name': 'Beldeport',
  'feature_type': 'port',
  'district': 'Körfez',
  'aliases': ('Beldeport', 'Beldeport Liman'),
  'source_key': 'beldeport',
  'allow_fuzzy': True},
 {'canonical_name': 'Yılport Yarımca Limanı',
  'feature_type': 'port',
  'district': 'Körfez',
  'aliases': ('Yılport Yarımca Limanı', 'Yarımca Limanı'),
  'source_key': 'diler_liman',
  'allow_fuzzy': True},
 {'canonical_name': 'Dilerport Dilovası',
  'feature_type': 'port',
  'district': 'Dilovası',
  'aliases': ('Dilerport Dilovası', 'Dilerport'),
  'source_key': 'diler_liman',
  'allow_fuzzy': True},
 {'canonical_name': 'Anadolu Otoyolu',
  'feature_type': 'road',
  'district': None,
  'aliases': ('Anadolu Otoyolu', 'TEM Otoyolu', 'O-4'),
  'source_key': 'kbb_muhtar_count_2024'},
 {'canonical_name': 'Kuzey Marmara Otoyolu',
  'feature_type': 'road',
  'district': None,
  'aliases': ('Kuzey Marmara Otoyolu',),
  'source_key': 'kbb_muhtar_count_2024'},
 {'canonical_name': 'D-100 Karayolu',
  'feature_type': 'road',
  'district': None,
  'aliases': ('D-100', 'D100', 'E-5', 'D-100 Karayolu'),
  'source_key': 'kbb_muhtar_count_2024'},
 {'canonical_name': 'D-130 Karayolu',
  'feature_type': 'road',
  'district': None,
  'aliases': ('D-130', 'D130', 'D-130 Karayolu'),
  'source_key': 'kbb_muhtar_count_2024'},
 {'canonical_name': 'Salim Dervişoğlu Caddesi',
  'feature_type': 'road',
  'district': 'İzmit',
  'aliases': ('Salim Dervişoğlu Caddesi',),
  'source_key': 'kbb_muhtar_count_2024'})

AREA_ENTRIES = ({'canonical_name': 'Değirmendere',
  'feature_type': 'area',
  'district': 'Gölcük',
  'aliases': ('Değirmendere',),
  'source_key': 'kocaelitime_muhtar_list_2020'},
 {'canonical_name': 'Halıdere',
  'feature_type': 'area',
  'district': 'Gölcük',
  'aliases': ('Halıdere',),
  'source_key': 'kocaelitime_muhtar_list_2020'},
 {'canonical_name': 'Hisareyn',
  'feature_type': 'area',
  'district': 'Gölcük',
  'aliases': ('Hisareyn', 'Hasaneyn'),
  'source_key': 'kocaelitime_muhtar_list_2020'},
 {'canonical_name': 'İhsaniye',
  'feature_type': 'area',
  'district': 'Gölcük',
  'aliases': ('İhsaniye',),
  'source_key': 'kocaelitime_muhtar_list_2020'},
 {'canonical_name': 'Ulaşlı',
  'feature_type': 'area',
  'district': 'Gölcük',
  'aliases': ('Ulaşlı',),
  'source_key': 'kocaelitime_muhtar_list_2020'},
 {'canonical_name': 'Akmeşe',
  'feature_type': 'area',
  'district': 'İzmit',
  'aliases': ('Akmeşe',),
  'source_key': 'kocaelitime_muhtar_list_2020'},
 {'canonical_name': 'Alikahya',
  'feature_type': 'area',
  'district': 'İzmit',
  'aliases': ('Alikahya',),
  'source_key': 'kocaelitime_muhtar_list_2020'},
 {'canonical_name': 'Kuruçeşme',
  'feature_type': 'area',
  'district': 'İzmit',
  'aliases': ('Kuruçeşme',),
  'source_key': 'kocaelitime_muhtar_list_2020'},
 {'canonical_name': 'Kullar',
  'feature_type': 'area',
  'district': 'Başiskele',
  'aliases': ('Kullar',),
  'source_key': 'kocaelitime_muhtar_list_2020'},
 {'canonical_name': 'Yuvacık',
  'feature_type': 'area',
  'district': 'Başiskele',
  'aliases': ('Yuvacık',),
  'source_key': 'kocaelitime_muhtar_list_2020'},
 {'canonical_name': 'Bahçecik',
  'feature_type': 'area',
  'district': 'Başiskele',
  'aliases': ('Bahçecik',),
  'source_key': 'kocaelitime_muhtar_list_2020'})

SOURCE_METADATA = {'kbb_muhtar_count_2024': {'label': 'Kocaeli Büyükşehir Belediyesi - 472 muhtara dizüstü bilgisayar',
                           'url': 'https://www.kocaeli.bel.tr/haber/buyuksehirden-472-muhtara-dizustu-bilgisayar-41219.html',
                           'kind': 'official',
                           'verified_on': '2026-04-03',
                           'notes': 'Kocaeli genelindeki 472 mahalle muhtarlığını resmi belediye haberiyle '
                                    'doğrular.'},
 'kocaelitime_muhtar_list_2020': {'label': 'Kocaeli Time - Kocaeli Geneli Mahalle Muhtarları (2019-2024)',
                                  'url': 'https://kocaelitime.com.tr/kocaeli-geneli-mahalle-muhtarlari-2019-2024/',
                                  'kind': 'secondary',
                                  'verified_on': '2026-04-03',
                                  'notes': '12 ilçedeki mahalle adlarının tam listesini sağlar; resmi 472 '
                                           'mahalle sayısı ile çapraz doğrulandı.'},
 'kbb_ormanya': {'label': 'Kocaeli Büyükşehir Belediyesi - Ormanya',
                 'url': 'https://www.kocaeli.bel.tr/hizmet/ormanya-26.html',
                 'kind': 'official',
                 'verified_on': '2026-04-03'},
 'kbb_bilim_merkezi': {'label': 'Kocaeli Büyükşehir Belediyesi - Kocaeli Bilim Merkezi',
                       'url': 'https://www.kocaeli.bel.tr/hizmet/kocaeli-bilim-merkezi-162.html',
                       'kind': 'official',
                       'verified_on': '2026-04-03'},
 'kbb_kongre_merkezi': {'label': 'Kocaeli Büyükşehir Belediyesi - Kocaeli Uluslararası Kongre Merkezi',
                        'url': 'https://www.kocaeli.bel.tr/hizmet/kocaeli-uluslararasi-kongre-merkezi-108.html',
                        'kind': 'official',
                        'verified_on': '2026-04-03'},
 'kbb_golcuk_kongre': {'label': 'Kocaeli Büyükşehir Belediyesi - Gölcük Kültür ve Kongre Merkezi',
                       'url': 'https://www.kocaeli.bel.tr/proje/golcuk-kultur-ve-kongre-merkezi-602.html',
                       'kind': 'official',
                       'verified_on': '2026-04-03'},
 'kbb_darica_kongre': {'label': 'Kocaeli Büyükşehir Belediyesi - Darıca Kültür ve Kongre Merkezi',
                       'url': 'https://www.kocaeli.bel.tr/proje/darica-kultur-ve-kongre-merkezi-599.html',
                       'kind': 'official',
                       'verified_on': '2026-04-03'},
 'kbb_korfez_kongre': {'label': 'Kocaeli Büyükşehir Belediyesi - Körfez Kongre Merkezi',
                       'url': 'https://www.kocaeli.bel.tr/proje/korfez-kongre-merkezi-600.html',
                       'kind': 'official',
                       'verified_on': '2026-04-03'},
 'kbb_sekapark': {'label': 'Kocaeli Büyükşehir Belediyesi - Sekapark',
                  'url': 'https://www.kocaeli.bel.tr/sekapark.html',
                  'kind': 'official',
                  'verified_on': '2026-04-03'},
 'ulasimpark_terminal': {'label': 'UlaşımPark - Terminal Konum',
                         'url': 'https://www.ulasimpark.com.tr/terminal/konum',
                         'kind': 'official',
                         'verified_on': '2026-04-03'},
 'tff_kocaeli_stadyumu': {'label': 'TFF - Kocaeli Stadyumu',
                          'url': 'https://www.tff.org/Default.aspx?kulupID=132&pageID=28',
                          'kind': 'official',
                          'verified_on': '2026-04-03'},
 'tff_gebze_stadyumu': {'label': 'TFF - Gebze Alaettin Kurt Stadyumu',
                        'url': 'https://www.tff.org/Default.aspx?macId=272774&pageID=29',
                        'kind': 'official',
                        'verified_on': '2026-04-03'},
 'tff_darica_stadyumu': {'label': 'TFF - Darıca İlçe Stadı',
                         'url': 'https://www.tff.org/Default.aspx?kulupId=3615&pageID=395',
                         'kind': 'official',
                         'verified_on': '2026-04-03'},
 'tff_karamursel_stadyumu': {'label': 'TFF - Karamursel Ilce',
                             'url': 'https://www.tff.org/Default.aspx?macId=308248&pageId=29',
                             'kind': 'official',
                             'verified_on': '2026-04-03'},
 'saglik_kocaeli_sehir': {'label': 'Kamu Hastaneleri Genel Müdürlüğü - Kocaeli Şehir Hastanesi',
                          'url': 'https://khgm.saglik.gov.tr/TR-95587/tc-saglik-bakanligi-kocaeli-sehir-hastanesi.html',
                          'kind': 'official',
                          'verified_on': '2026-04-03'},
 'saglik_kocaeli_devlet': {'label': 'Kocaeli Devlet Hastanesi',
                           'url': 'https://kocaelidh.saglik.gov.tr/',
                           'kind': 'official',
                           'verified_on': '2026-04-03'},
 'saglik_derince_eah': {'label': 'Sağlık Türkiye - Derince Eğitim ve Araştırma Hastanesi',
                        'url': 'https://www.healthturkiye.gov.tr/tr/hospital/t.c.-saglik-bakanligi-sbu-derince-egitim-ve-arastirma-hastanesi',
                        'kind': 'official',
                        'verified_on': '2026-04-03'},
 'saglik_gebze_fatih': {'label': 'Gebze Fatih Devlet Hastanesi',
                        'url': 'https://gebzefatih.saglik.gov.tr/TR-116717/gebze-fatih-devlet-hastanesi-merkez-yerleskesi.html',
                        'kind': 'official',
                        'verified_on': '2026-04-03'},
 'saglik_darica_farabi': {'label': 'Darıca Farabi Eğitim ve Araştırma Hastanesi',
                          'url': 'https://daricafarabieah.saglik.gov.tr/Default.aspx',
                          'kind': 'official',
                          'verified_on': '2026-04-03'},
 'saglik_ozel_tesisler': {'label': 'Kocaeli İl Sağlık Müdürlüğü - Özel Sağlık Tesislerimiz',
                          'url': 'https://kocaeliism.saglik.gov.tr/TR-242144/ozel-tip-merkezleri.html',
                          'kind': 'official',
                          'verified_on': '2026-04-03'},
 'kocaeli_uni': {'label': 'Kocaeli Üniversitesi - Umuttepe İletişim Sayfaları',
                 'url': 'https://avesis.kocaeli.edu.tr/umit.alniacik/iletisim',
                 'kind': 'official',
                 'verified_on': '2026-04-03'},
 'gtu_kampus': {'label': 'Gebze Teknik Üniversitesi - Kampüs Haritası',
                'url': 'https://www.gtu.edu.tr/icerik/973/689/kampus-haritasi.aspx',
                'kind': 'official',
                'verified_on': '2026-04-03'},
 'cineverse_41burda': {'label': 'Paribu Cineverse - 41 Burda',
                       'url': 'https://www.paribucineverse.com/sinemalar/41-burda',
                       'kind': 'official',
                       'verified_on': '2026-04-03'},
 'cineverse_gebze_center': {'label': 'Paribu Cineverse - Gebze Center',
                            'url': 'https://www.paribucineverse.com/sinemalar/gebze-center',
                            'kind': 'official',
                            'verified_on': '2026-04-03'},
 'symbol_sinema': {'label': 'Symbol AVM - Sinema',
                   'url': 'https://symbolkocaeli.com/sinema',
                   'kind': 'official',
                   'verified_on': '2026-04-03'},
 'beldeport': {'label': 'Beldeport Liman',
               'url': 'https://www.beldeport.com.tr/tr-TR/liman/241',
               'kind': 'official',
               'verified_on': '2026-04-03'},
 'diler_liman': {'label': 'Diler Holding - Limanlar',
                 'url': 'https://www.dilerhld.com/grup.asp?anagrup_no=5',
                 'kind': 'official',
                 'verified_on': '2026-04-03'}}
